mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include # import include function



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('searchpage.urls')),
]

mysite/searchpage/urls.py
# myapp/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from .views import home, search_page, repeat

app_name = 'searchpage'

urlpatterns = [

    re_path(r'page/$',repeat,name="page"),
    re_path(r'search/$', search_page, name="search"),
    path('', home, name="homepage"),
]

mysite/searchpage/models.py
from django.db import models
# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True,null=True)

mysite/searchpage/views.py
from django.shortcuts import render, redirect
from .models import Product
from .Search import Search

def home(request):
    return render(request,'searchpage/home.html')

def search_page(request):

    data = request.POST.get('search')
    print(data)
    object_search = Search(data)
    if object_search != "not found":
        results = object_search.Start_search()
    else:
        print("jjjjjjjjjjjjj")
        results = "not found"
    return render(request,'searchpage/search.html',{"dic":results,"data":data})

def repeat(request):
    data = request.POST.get('search')
    print(data)
    object_search = Search(data)
    if object_search != "not found":
        results = object_search.Start_search()
    else:
        results = "not found"
    return render(request,'searchpage/search.html',{"dic":results,"data":data})


def mong(request):
    obj = Product.objects.get(id=1)
    context = {
        'title':obj.title,
        'description':obj.descriptio
    }
    return render(request,"product/detail.html",context)

mysite/searchpage/templates/searchpage/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NEG Search Engine</title>
    <style>
	    body{
		    background-color: #0E0D0D;
	    }
	    img {
		    display: block;
		    margin-left: auto;
		    margin-right: auto;
		    width: 200px;
		    height: 250px;
	    }
	    p{
		    font-size:30px;
		    font-family: "Garamond", Times, serif;
		    color: white;
	    }
	    @import url("https://fonts.googleapis.com/css?family=Roboto:400,400i,700");

	    * {
		    font-family: Roboto, sans-serif;
		    padding: 0;
		    margin: 0;
	    }
	    .flexbox{
		    text-align: center;
	    }
	    .search {
		    margin: 20px;
	    }

	    .search > h3 {
		    font-weight: normal;
	    }

	    .search > h1,
	    .search > h3 {
		    color: white;
		    margin-bottom: 15px;
		    text-shadow: 0 1px #0091c2;
	    }

	    .search > div {
		    display: inline-block;
		    position: relative;
		    filter: drop-shadow(0 1px #0091c2);
	    }

	    .search > div:after {
		    content: "";
		    background: white;
		    width: 4px;
		    height: 20px;
		    position: absolute;
		    top: 40px;
		    right: 2px;
		    transform: rotate(135deg);
	    }

	    .search > div > input {

	    	color: white;
		    font-size: 20px;
		    background: transparent;
		    font-family: "Garamond", Times, serif;
		    width: 25px;
		    height: 25px;
		    padding: 10px;
		    border: solid 3px white;
		    outline: none;
		    border-radius: 35px;
	    	transition: width 0.5s;
	    }

	    .search > div > input::placeholder {
		    color: #efefef;
		    opacity: 0;
		    transition: opacity 150ms ease-out;
	    }

	    .search > div > input:focus::placeholder {
		    opacity: 1;
	    }

	    .search > div > input:focus,
	    .search > div > input:not(:placeholder-shown) {
		    width: 400px;
	    }

	    .buttonSearch{
	    	color: white;
	    	font-family: "Garamond", Times, serif;
	    	background-color: #0E0D0D;
	    	text-align: center;
	    	align-items: center;
	    	justify-content: center;
			vertical-align:middle;
			display: block;
    		height: 30px;
    		width: 70px;
    		margin: 0 auto;
    		border: none;
    		outline:none;
 		    font-size: 20px;



	    }

    </style>
</head>
<body>
<form action="{% url 'searchpage:search' %}" method="post">
	{% csrf_token %}
	<input type="hidden" name="title" value="{{ source.title }}">
	<img src="https://lh3.googleusercontent.com/190XKrQmG_JXIRzPRD0IiOO4ZtOd9pTgEzey-HTsSrTwOAl4jXP6XkEiq99vZRT9S9oVmAH3hVrH8Z-4xiSd2Xeyb4DfE62Mvo5q79Q0za5c8fDkIDpY_yBQKsNt1IQJ4uyh3jpq=w2400?source=screenshot.guru" alt="search engine">
	<div class="flexbox">
		<div class="search">
			<p>Start your searching</p>
			<div>
				<input type="text" placeholder="Search . . ." name="search" id="search" required autocomplete="off">
			</div>
		</div>
	</div>
	<input type="submit" value="Search" name="submit" class="buttonSearch">

</form>
</body>
</html>

mysite/searchpage/templates/searchpage/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NEG Search Engine</title>
    <style>
	    body{
		    background-color: #0E0D0D;
	    }
	    div.container{
   		    width: 700px;

	    }
	    a{
	    	font-size:25px;
		    font-family: "Garamond", Times, serif;
		    color: darkorchid;
	    }
	    img {
		    display: block;
		    margin-left: auto;
		    margin-right: auto;
		    width: 55px;
			float: right;
		    height: 70px;
			position: absolute;
			left: 900px;
			top: 5px;

	    }
	    script{
	    	font-size:16px;
		    font-family: "Garamond", Times, serif;
		    color: white;
		    word-break:  keep-all;
	    }
	    p{
		    font-size:16px;
		    font-family: "Garamond", Times, serif;
		    color: white;
		    word-break:  keep-all;
	    }
	    p.error{
		    font-size:25px;
		    font-family: "Garamond", Times, serif;
		    color: white;
		    word-break:  keep-all;
	    }
	    @import url("https://fonts.googleapis.com/css?family=Roboto:400,400i,700");

	    * {
		    font-family: Roboto, sans-serif;
		    padding: 0;
		    margin: 0;
	    }
	    .flexbox{
		    text-align: center;
	    }
	    .search {
		    margin: 20px;
	    }

	    .search > div {
		    position: relative;
		    filter: drop-shadow(0 1px #0091c2);
	    }

	    .search > div > input {

	    	color: white;
		    font-size: 20px;
		    background: transparent;
		    font-family: "Garamond", Times, serif;
		    width: 500px;
		    height: 25px;
		    padding: 10px;
		    border: solid 3px white;
		    outline: none;
			direction: rtl;
		    border-radius: 35px;

	    }

	    .buttonSearch{
	    	color: white;
	    	font-family: "Garamond", Times, serif;
	    	background-color: #0E0D0D;
	    	text-align: center;
	    	align-items: center;
	    	justify-content: center;
			vertical-align:middle;
			display: block;
    		height: 30px;
    		width: 70px;
    		margin: 0 auto;
    		border: none;
    		outline:none;
 		    font-size: 20px;
			position: absolute;
			left: 400px;
			top: 5px;




	    }

    </style>
</head>
<body>
<form action="{% url 'searchpage:page' %}" method="post">
	{% csrf_token %}
<input type="hidden" name="title" value="{{ source.title }}">
	<img src="https://lh3.googleusercontent.com/190XKrQmG_JXIRzPRD0IiOO4ZtOd9pTgEzey-HTsSrTwOAl4jXP6XkEiq99vZRT9S9oVmAH3hVrH8Z-4xiSd2Xeyb4DfE62Mvo5q79Q0za5c8fDkIDpY_yBQKsNt1IQJ4uyh3jpq=w2400?source=screenshot.guru" alt="search engine">
	<div class="flexbox">
		<div class="search">
			<div>
				<input type="text" value="{{data}}" name="search" id="search" required autocomplete="off">
			</div>
		</div>
	</div>
	<input type="submit" value="Search" name="submit" class="buttonSearch">


	{% if dic == "not found" %}
    	<p class="error"> no results found </p>
   {% endif %}

	{% for key,value in dic.items %}
		<br>
		<div class="container">
			<li><a href="{{key}}">{{value.title}}</a></li>
			<p id="demo1">{{value.description}}</p>
		</div>
		<br>
	{% endfor %}
	<h1 style="color:white;">
		{{title}}
	</h1>
</form>
</body>
</html>